#!/bin/bash
#
# chkconfig: 345 99 28
# description: Starts/Stops Zookeeper
#

SHUTDOWN_WAIT=20
SERVER=/home/zoo/current/bin/zkServer.sh

pid() {
    echo `ps -fe | grep conf/zoo.cfg | grep -v grep | tr -s " "|cut -d" " -f2`
}

start() {
    su zoo -c "ZOO_LOG_DIR={{Z_DATA_DIR}} $SERVER start"
    return $?
}
 
status() {
    su zoo -c "$SERVER status"
    return $?
}
 
stop() {
    su zoo -c "$SERVER stop"
    return $?
}

case $1 in
 
    start)
        start
    ;;
       
    stop)  
        stop
    ;;
       
    restart)
        stop
        start
    ;;
       
    status)
        status
    ;;
       
    *)
        echo -e $USAGE
    ;;

esac    
exit $?
